name: Deploy Flask Python API to AWS

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS server
        run: |
          echo "Creating test_deployment file on AWS server"
          echo "$AWS_SSH_KEY" > key.pem
          chmod 400 key.pem
          scp -i key.pem requirements.txt ubuntu@13.42.225.186:~/
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}