name: Build, Push Docker Image and Deploy Flask Python API to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          omoi/webcrawler:latest
          omoi/webcrawler:${{ github.sha }}

    - name: Deploy to AWS server
      run: |
        echo "Creating test_deployment file on AWS server"
        echo "$AWS_SSH_KEY" > key.pem
        chmod 400 key.pem
        scp -o StrictHostKeyChecking=no -i key.pem your_file.txt ubuntu@13.42.225.186:~/
      env:
        AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
